/*
###############################################################
#  Generated by:      Cadence Innovus 18.13-s088_1
#  OS:                Linux x86_64(Host ID zxp007.u-aizu.ac.jp)
#  Generated on:      Tue Nov 21 14:21:58 2023
#  Design:            top
#  Command:           saveNetlist ./output_files/top.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 18.13-s027_1
// Generated on: Nov 20 2023 10:34:16 JST (Nov 20 2023 01:34:16 UTC)
// Verification Directory fv/top 
module top (
	clk, 
	rst_n, 
	input1, 
	input2, 
	output1);
   input clk;
   input rst_n;
   input [7:0] input1;
   input [7:0] input2;
   output [7:0] output1;

   // Internal wires
   wire [7:0] r_temp2;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;

   TSV \TSV_GEN[0].TSV0  (.data_in(r_temp2[0]),
	.data_out(output1[0]));
   TSV \TSV_GEN[1].TSV0  (.data_in(r_temp2[1]),
	.data_out(output1[1]));
   TSV \TSV_GEN[2].TSV0  (.data_in(r_temp2[2]),
	.data_out(output1[2]));
   TSV \TSV_GEN[3].TSV0  (.data_in(r_temp2[3]),
	.data_out(output1[3]));
   TSV \TSV_GEN[4].TSV0  (.data_in(r_temp2[4]),
	.data_out(output1[4]));
   TSV \TSV_GEN[5].TSV0  (.data_in(r_temp2[5]),
	.data_out(output1[5]));
   TSV \TSV_GEN[6].TSV0  (.data_in(r_temp2[6]),
	.data_out(output1[6]));
   TSV \TSV_GEN[7].TSV0  (.data_in(r_temp2[7]),
	.data_out(output1[7]));
   DFFR_X1 \r_temp2_reg[7]  (.D(n_15),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[7]),
	.QN(UNCONNECTED));
   XNOR2_X1 g650 (.A(n_13),
	.B(n_0),
	.ZN(n_15));
   DFFR_X1 \r_temp2_reg[6]  (.D(n_14),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[6]),
	.QN(UNCONNECTED0));
   FA_X1 g652 (.A(input2[6]),
	.B(input1[6]),
	.CI(n_11),
	.CO(n_13),
	.S(n_14));
   DFFR_X1 \r_temp2_reg[5]  (.D(n_12),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[5]),
	.QN(UNCONNECTED1));
   FA_X1 g654 (.A(input2[5]),
	.B(input1[5]),
	.CI(n_9),
	.CO(n_11),
	.S(n_12));
   DFFR_X1 \r_temp2_reg[4]  (.D(n_10),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[4]),
	.QN(UNCONNECTED2));
   FA_X1 g656 (.A(input2[4]),
	.B(input1[4]),
	.CI(n_7),
	.CO(n_9),
	.S(n_10));
   DFFR_X1 \r_temp2_reg[3]  (.D(n_8),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[3]),
	.QN(UNCONNECTED3));
   FA_X1 g658 (.A(input2[3]),
	.B(input1[3]),
	.CI(n_5),
	.CO(n_7),
	.S(n_8));
   DFFR_X1 \r_temp2_reg[2]  (.D(n_6),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[2]),
	.QN(UNCONNECTED4));
   FA_X1 g660 (.A(input2[2]),
	.B(input1[2]),
	.CI(n_3),
	.CO(n_5),
	.S(n_6));
   DFFR_X1 \r_temp2_reg[1]  (.D(n_4),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[1]),
	.QN(UNCONNECTED5));
   FA_X1 g662 (.A(input2[1]),
	.B(input1[1]),
	.CI(n_1),
	.CO(n_3),
	.S(n_4));
   DFFR_X1 \r_temp2_reg[0]  (.D(n_2),
	.RN(rst_n),
	.CK(clk),
	.Q(r_temp2[0]),
	.QN(UNCONNECTED6));
   HA_X1 g664 (.A(input2[0]),
	.B(input1[0]),
	.CO(n_1),
	.S(n_2));
   XNOR2_X1 g665 (.A(input2[7]),
	.B(input1[7]),
	.ZN(n_0));
endmodule

