
// Generated by Cadence Genus(TM) Synthesis Solution 18.13-s027_1
// Generated on: Nov 20 2023 10:34:16 JST (Nov 20 2023 01:34:16 UTC)

// Verification Directory fv/top 

module top(clk, rst_n, input1, input2, output1);
  input clk, rst_n;
  input [7:0] input1, input2;
  output [7:0] output1;
  wire clk, rst_n;
  wire [7:0] input1, input2;
  wire [7:0] output1;
  wire [7:0] r_temp2;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  TSV \TSV_GEN[0].TSV0 (.data_in (r_temp2[0]), .data_out (output1[0]));
  TSV \TSV_GEN[1].TSV0 (.data_in (r_temp2[1]), .data_out (output1[1]));
  TSV \TSV_GEN[2].TSV0 (.data_in (r_temp2[2]), .data_out (output1[2]));
  TSV \TSV_GEN[3].TSV0 (.data_in (r_temp2[3]), .data_out (output1[3]));
  TSV \TSV_GEN[4].TSV0 (.data_in (r_temp2[4]), .data_out (output1[4]));
  TSV \TSV_GEN[5].TSV0 (.data_in (r_temp2[5]), .data_out (output1[5]));
  TSV \TSV_GEN[6].TSV0 (.data_in (r_temp2[6]), .data_out (output1[6]));
  TSV \TSV_GEN[7].TSV0 (.data_in (r_temp2[7]), .data_out (output1[7]));
  DFFR_X1 \r_temp2_reg[7] (.RN (rst_n), .CK (clk), .D (n_15), .Q
       (r_temp2[7]), .QN (UNCONNECTED));
  XNOR2_X1 g650(.A (n_13), .B (n_0), .ZN (n_15));
  DFFR_X1 \r_temp2_reg[6] (.RN (rst_n), .CK (clk), .D (n_14), .Q
       (r_temp2[6]), .QN (UNCONNECTED0));
  FA_X1 g652(.A (input2[6]), .B (input1[6]), .CI (n_11), .CO (n_13), .S
       (n_14));
  DFFR_X1 \r_temp2_reg[5] (.RN (rst_n), .CK (clk), .D (n_12), .Q
       (r_temp2[5]), .QN (UNCONNECTED1));
  FA_X1 g654(.A (input2[5]), .B (input1[5]), .CI (n_9), .CO (n_11), .S
       (n_12));
  DFFR_X1 \r_temp2_reg[4] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (r_temp2[4]), .QN (UNCONNECTED2));
  FA_X1 g656(.A (input2[4]), .B (input1[4]), .CI (n_7), .CO (n_9), .S
       (n_10));
  DFFR_X1 \r_temp2_reg[3] (.RN (rst_n), .CK (clk), .D (n_8), .Q
       (r_temp2[3]), .QN (UNCONNECTED3));
  FA_X1 g658(.A (input2[3]), .B (input1[3]), .CI (n_5), .CO (n_7), .S
       (n_8));
  DFFR_X1 \r_temp2_reg[2] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (r_temp2[2]), .QN (UNCONNECTED4));
  FA_X1 g660(.A (input2[2]), .B (input1[2]), .CI (n_3), .CO (n_5), .S
       (n_6));
  DFFR_X1 \r_temp2_reg[1] (.RN (rst_n), .CK (clk), .D (n_4), .Q
       (r_temp2[1]), .QN (UNCONNECTED5));
  FA_X1 g662(.A (input2[1]), .B (input1[1]), .CI (n_1), .CO (n_3), .S
       (n_4));
  DFFR_X1 \r_temp2_reg[0] (.RN (rst_n), .CK (clk), .D (n_2), .Q
       (r_temp2[0]), .QN (UNCONNECTED6));
  HA_X1 g664(.A (input2[0]), .B (input1[0]), .CO (n_1), .S (n_2));
  XNOR2_X1 g665(.A (input2[7]), .B (input1[7]), .ZN (n_0));
endmodule

