
// Generated by Cadence Genus(TM) Synthesis Solution 18.13-s027_1
// Generated on: Nov 16 2023 15:13:28 JST (Nov 16 2023 06:13:28 UTC)

// Verification Directory fv/detector110 

module detector110(a, clk, reset, w);
  input a, clk, reset;
  output w;
  wire a, clk, reset;
  wire w;
  wire [1:0] state;
  wire UNCONNECTED, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  DFF_X1 \state_reg[0] (.CK (clk), .D (n_7), .Q (state[0]), .QN (n_3));
  DFF_X1 \state_reg[1] (.CK (clk), .D (n_8), .Q (state[1]), .QN
       (UNCONNECTED));
  OAI21_X1 g218(.A (n_6), .B1 (n_5), .B2 (n_3), .ZN (n_8));
  OAI222_X1 g217(.A1 (n_6), .A2 (a), .B1 (n_5), .B2 (state[0]), .C1
       (n_0), .C2 (n_4), .ZN (n_7));
  OR2_X1 g219(.A1 (state[1]), .A2 (n_4), .ZN (n_5));
  NAND3_X1 g220(.A1 (state[1]), .A2 (n_3), .A3 (n_2), .ZN (n_6));
  NAND2_X1 g221(.A1 (n_2), .A2 (a), .ZN (n_4));
  INV_X1 g222(.A (n_0), .ZN (w));
  NAND2_X1 g223(.A1 (state[1]), .A2 (state[0]), .ZN (n_0));
  INV_X1 g224(.A (reset), .ZN (n_2));
endmodule

